### ISSUE TITLE
Export `encodeRecord`

### ISSUE THREAD

**Issue by Gabriel439** [tibbe/cassava#44]
Right now the only way to encode csv files is to build a `Vector Record`, which means that my input has to be fully loaded into memory before I can begin encoding.  However, I would like to be able to generate `Record`s on the fly (i.e. using `pipes`) and stream them to a file without going through an intermediate `Vector Record` representation.

I was studying the source code and I see that `cassava` uses `encodeRecord` internally, which is basically the function I would like to use.  I could obviously copy and paste its functionality, but I wanted to first try to ask if you could re-export it instead.

**Comment by tibbe** [comment]
Check out 0.4.3.0.

**Comment by jb55** [comment]
Thanks!
