### ISSUE TITLE
allow index-based access while retaining information about the header

### ISSUE THREAD

**Issue by mwotton** [tibbe/cassava#75]
I've hit the problem a few times now while writing generic CSV manipulation code: i sometimes want to parse something where I don't know the headers up-front, but they are relevant to the result. For instance - i'm currently writing a csv merge tool that looks at a list of csv files, with differing headers, and creates a single csv file consisting of the superset of the headers, with a default value for missing values.

```
decode :: FromRecord a
=> HasHeader	
-> ByteString	
-> Either String (Vector a)
```

would work fine, except I don't get access to the header without reparsing with decodeByName, which seems wasteful.

on the other hand, if I use decodeByName directly, I end up with this abomination:

```
newtype SemrushRow = SemrushRow {
  unSemRushRow :: Csv.Header -> [(String,Text)]
}

instance FromNamedRecord (SemrushRow) where
   parseNamedRecord m = return . SemrushRow $ \header ->
     zip (map BS.unpack $ V.toList header)
         (V.toList $ V.map (decodeUtf8 . fromJust . (`HM.lookup` m)) header)
```

which is dreadful in more ways than i can count.

**Comment by tibbe** [comment]
Couldn't you call `decodeByName` on every file individually and take advantage of the `HashMap` `FromNamedRecord` instance to end up with `[(Header, Vector (HashMap ByteString ByteString))]`. You can then merge all the vectors and provide default values as you go.

**Comment by mwotton** [comment]
yes. That's effectively the second approach. It's just annoyingly verbose, and i'd still need to do the equivalent of fromJust because I know the lookups are safe.

In the end it was less code to just pretend it didn't have a header and use decode, then pull the header out myself.

**Comment by sol** [comment]
@tibbe I also want to get the headers with index based access.  Currently, for my specific use case, 60% of cpu and 48% of allocation is spent on access the `HashMap`.

I'll probably go for a similar workaround as @mwotton for now.
