### ISSUE TITLE
encodeOption to allow quoting all strings

### ISSUE THREAD

**Issue by mwotton** [tibbe/cassava#80]
currently it only adds doublequotes when it would be "necessary" - unfortunately, when i want to encode a number as a string because Excel is braindead ( https://support.microsoft.com/en-us/kb/269370 ), the quotes get stripped, and Excel breaks it if the number is longer than 15 digits.

**Comment by tibbe** [comment]
That makes sense. We should have an option for no quotes, required quotes (according to the standard), and all quotes. Python's csv library does this.

**Comment by jcristovao** [comment]
I would definitely welcome this... my use case is the exact oposite, I would like ```QuoteNone```.
I could take a stab at this, but perhaps I'm tired, I'm not really seeing where the current behavior is implemented. Is it implicit?
Thanks

**Comment by tibbe** [comment]
@jcristovao https://github.com/tibbe/cassava/blob/master/Data/Csv/Encoding.hs#L214

**Comment by jcristovao** [comment]
Great, I see it now, its the encode function. I'll try to address this...
Em 30/04/2015 18:32, "Johan Tibell" <notifications@github.com> escreveu:

**Comment by tibbe** [comment]
Fixed by e1aae941f85338985f3c54529775039c535ced7d & co.
