### ISSUE TITLE
GHC-7.10.1 compatibility

### ISSUE THREAD

**Issue by nomeata** [tibbe/cassava#81]
Hi,

if Travis is not misleading me, then cassava has no version compatible with GHC-7.10.1 (which ships `ghc-prim-0.4`) due to `ghc-prim (>=0.2 && <0.4)`.

Thanks,
Joachim

**Comment by osa1** [comment]
:+1: I need this too. I think every benchmark program that uses on Criterion is now broken because of this.

**Comment by hvr** [comment]
Btw, `cassava` probably doesn't need `ghc-prim` anymore for GHC >= 7.6 anyway...

**Comment by holzensp** [comment]
FYI, building it without the ghc-prim dependency and relaxing blaze-builder to < 0.5 (instead of < 0.4) works for me (i.e. passes cabal config / cabal build / cabal test)

**Comment by tibbe** [comment]
Fixed.
